# Generated by Django 5.1.2 on 2024-11-30 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cited_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cited_papers', to='papers.paper')),
                ('citing_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citing_papers', to='papers.paper')),
            ],
        ),
    ]
